services:
  mmdetection:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: openmmlab/mmdetection:0.1
    container_name: mmdetection
    volumes:
      - ../:/mmdetection    
    shm_size: "8gb"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8888:8888